### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by lukecav** [skopco/powered-cache#2]
Warning: session_start(): user session functions not defined in /srv/bindings/b8df0cbe5ab440b6a34e6102e96bb940/code/wp-content/plugins/powered-cache/includes/admin/class-pc-admin.php on line 42 Fatal error: session_start(): Failed to initialize storage module: user (path: ) in /srv/bindings/b8df0cbe5ab440b6a34e6102e96bb940/code/wp-content/plugins/powered-cache/includes/admin/class-pc-admin.php on line 42

https://github.com/skopco/powered-cache/blob/master/includes/admin/class-pc-admin.php#L42

**Comment by mustafauysal** [comment]
Hi @lukecav,

Can you provide detail about hosting env. Is it PHP7 or safe mode on?

**Comment by lukecav** [comment]
It was on a Pantheon dev site. Was able to activate the plugin on a live test site fine.

**Comment by mustafauysal** [comment]
Ok, thanks for feedback. 

Currently using session for flash messaging purpose, I think we can handle those messages by using `add_query_arg`

Btw, this plugin approved for wp.org,  feedbacks are appreciated before releasing stable version :)

**Comment by mustafauysal** [comment]
started using transient cache (in f8f453b1e8c0a0ab4598e89c1d60a776363eb32b) for flash messages.

Please update and try to activate again.

**Comment by mustafauysal** [comment]
Hi @lukecav,

I think this problem no longer exists. So I'm closing this issue, feel free to reopen if the problem persistent.
